# Generated by Django 4.1.7 on 2023-03-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_remove_comment_name_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reads",
            field=models.IntegerField(default=0),
        ),
    ]
