# Generated by Django 4.1.7 on 2023-03-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0014_post_comments_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
