# Generated by Django 4.1.7 on 2023-03-13 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_remove_post_comments_count_remove_post_reads_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="user",
        ),
    ]
