# Generated by Django 4.1.7 on 2023-03-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_remove_comment_post_remove_comment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reads",
            field=models.IntegerField(default=0),
        ),
    ]
