# Generated by Django 4.1.7 on 2023-03-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_comment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="comments_count",
            field=models.IntegerField(default=0),
        ),
    ]
