# Generated by Django 4.1.7 on 2023-03-16 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_remove_comment_parent_comment_reply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reply",
            options={"verbose_name_plural": "Replies"},
        ),
    ]
